import { AppView } from '../../types';

export const ROUTES_MAP: Record<AppView, string> = {
  LANDING: '/',
  HOME: '/home',
  SELECT_CATEGORY: '/agendar/categoria',
  SELECT_SERVICES: '/agendar/servicos',
  SELECT_PROFESSIONAL: '/agendar/profissional',
  SELECT_DATE_TIME: '/agendar/data-hora',
  CUSTOMER_INFO: '/cliente',
  REVIEW: '/agendar/revisar',
  MY_APPOINTMENTS: '/agendamentos',
  LOGIN: '/login',
  ADMIN_DASHBOARD: '/admin',
  CHAT: '/chat',
  ADMIN_SERVICES: '/admin/servicos',
  ADMIN_CHAT_LIST: '/admin/chat',
  ADMIN_BLOCK_SCHEDULE: '/admin/bloqueios',
  ADMIN_SETTINGS: '/admin/configuracoes',
  ADMIN_FINANCE: '/admin/financeiro',
  ADMIN_TV: '/admin/tv',
  SELECT_PLAN: '/assinaturas/planos',
  SUBSCRIPTION_PAYMENT: '/assinaturas/pagamento',
  ADMIN_PROFESSIONALS: '/admin/equipe',
  ADMIN_PRODUCTS: '/admin/produtos',
  PRODUCTS: '/produtos',
  ADMIN_WEEKLY_SCHEDULE: '/admin/horarios',
  CUSTOMER_LOGIN: '/entrar',
  ADMIN_CLIENTS: '/admin/clientes',
  ADMIN_CLUB: '/admin/clube',
};
